CREATE	DATABASE PROJETO_X;
USE PROJETO_X;

CREATE TABLE projeto_x.DADOSUSUARIO(
ID INT AUTO_INCREMENT,
NOME varchar(50),
USERNAME varchar(50),
SENHA varchar(50),
CARGO varchar(50),
FILIAL varchar(50),
constraint pk_id primary key (id)
);
/**
 * Author:  Johnnys Dantas
 * Created: 03/05/2019
 */

CREATE TABLE DADOSCLIENTE(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50),
    EMAIL VARCHAR(80),
    CPF LONG,
    CNPJ LONG,
    TELEFONE VARCHAR(15),
    ENDERECO VARCHAR(255),
    NUMERO INT,
    COMPLEMENTO VARCHAR (30),
    ESTADO VARCHAR (30),
    CIDADE VARCHAR (30),
    BAIRRO VARCHAR (30),
    CEP VARCHAR (15),
    TIPO VARCHAR(1)
);

CREATE TABLE ESTOQUE(
	PK_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DS_DESCRICAO VARCHAR(50),
    DS_FILIAL VARCHAR(5)
);
